#!/usr/bin/env bash

cd $1
rm logbestand
touch logbestand
files=$(find . )

for file in $files
do
        command=$( sudo $2 $file )
        if [ $? == 0]
        then
                echo $file "geslaagd" | sudo tee -a /home/hu/Desktop/shellscripting/logbestand

        else
                echo $file "niet geslaagd" | sudo tee -a /home/hu/Desktop/shellscripting/logbestand

        fi
done